title: archiveweb.page User Guide
description: User guide for webrecorder's archiveweb.page Chrome extension.

# Build settings
remote_theme:  pmarsceill/just-the-docs
plugins:
  - jekyll-feed


search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Back to ArchiveWeb.page":
    - "/"

logo: "/assets/images/awp-logo.svg"

